Reworking delete-branch to delete multiple branches in series

diff --git a/bin/git-delete-branch b/bin/git-delete-branch
--- a/bin/git-delete-branch
+++ b/bin/git-delete-branch
@@ -1,7 +1,10 @@
 #!/bin/sh
 
-branch=$1
-test -z $branch && echo "branch required." 1>&2 && exit 1
-git branch -D $branch
-git branch -d -r origin/$branch
-git push origin :refs/heads/$branch
+test -z $1 && echo "branch required." 1>&2 && exit 1
+
+for branch in "$@"
+do
+  git branch -D $branch
+  git branch -d -r origin/$branch
+  git push origin :refs/heads/$branch
+done
